/*
 * common.hpp
 *
 *  Created on: Jan 25, 2018
 *      Author: unni
 */

#ifndef COMMON_HPP_
#define COMMON_HPP_

#define TASK_TICK_10MS	(1)
#define TASK_TICK_20MS	(TASK_TICK_10MS * 2)
#define TASK_TICK_50MS	(TASK_TICK_10MS * 5)
#define TASK_TICK_100MS	(TASK_TICK_10MS * 10)
#define TASK_TICK_200MS	(TASK_TICK_100MS * 2)
#define TASK_TICK_500MS	(TASK_TICK_100MS * 5)
#define TASK_TICK_1SECOND (TASK_TICK_10MS * 100)

typedef enum
{
	TASK_CREATE_RESPONSE_INVALID = -1,
	TASK_CREATE_RESPONSE_SUCCESS,
	TASK_CREATE_RESPONSE_FAILURE,
	TASK_CREATE_RESPONSE_MAX
}eTaskCreateResponse;



#endif /* COMMON_HPP_ */
